apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wordpress
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wordpress
    spec:
      containers:
        - name: wordpress
          image: "{{ .Values.wordpress.image.repository }}:{{ .Values.wordpress.image.tag }}"
          env:
            - name: WORDPRESS_USERNAME
              value: "{{ .Values.wordpress.username }}"
            - name: WORDPRESS_PASSWORD
              value: "{{ .Values.wordpress.password }}"
            - name: WORDPRESS_EMAIL
              value: "{{ .Values.wordpress.email }}"
            - name: WORDPRESS_DATABASE_HOST
              value: "{{ .Release.Name }}-mysql"
            - name: WORDPRESS_DATABASE_NAME
              value: "{{ .Values.mysql.auth.database }}"
            - name: WORDPRESS_DATABASE_USER
              value: "{{ .Values.mysql.auth.username }}"
            - name: WORDPRESS_DATABASE_PASSWORD
              value: "{{ .Values.mysql.auth.password }}"
          ports:
            - containerPort: 8080
