apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
spec:
  type: {{ .Values.wordpress.service.type }}
  ports:
    - port: {{ .Values.wordpress.service.port }}
      targetPort: {{ .Values.wordpress.service.targetPort }}
      nodePort: {{ .Values.wordpress.service.nodePort }}
  selector:
    app: {{ .Release.Name }}-wordpress
